apply plugin: 'com.android.application'

android {
    compileSdkVersion 33
    buildToolsVersion "33.0.0"
    namespace 'io.agora.api.example'

    defaultConfig {
        applicationId "io.agora.api.example"
        minSdkVersion 19
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        buildConfig = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])

    def agora_sdk_version = "4.2.0"
    // case 1: full single lib
    implementation "io.agora.rtc:full-sdk:${agora_sdk_version}"
    implementation "io.agora.rtc:full-screen-sharing:${agora_sdk_version}"
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.appcompat:appcompat:1.2.0'

    def nav_version = "2.5.3"
    implementation "androidx.navigation:navigation-fragment:$nav_version"
    implementation "androidx.navigation:navigation-ui:$nav_version"

/*    // Java language implementation
    implementation "androidx.navigation:navigation-fragment:2.3.5-alpha06"
    implementation "androidx.navigation:navigation-ui:2.3.5-alpha06"*/
    implementation 'com.github.getActivity:XXPermissions:20.0'

    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'

    implementation 'de.javagl:obj:0.2.1'
}
